version: '3.8'

services:
  database:
    container_name: metric-database
    image: postgres:15.3
    environment:
      POSTGRES_DB: metric
      POSTGRES_USER: metric
      POSTGRES_PASSWORD: metric123
      PGDATA: /data/postgres
    ports:
      - '5400:5432'
    restart: on-failure
    volumes:
      - database:/data/postgres

volumes:
  database:
    name: metric-database
